-- Simple Conversion of Production Orders to LG Products
-- This script transforms existing AppProductionOrders data into LG products

-- Clear existing LG products
DELETE FROM [dbo].[AppProducts] WHERE Brand = 'LG';

-- Insert LG Products based on Production Orders
INSERT INTO [dbo].[AppProducts] (
    [Id],
    [ProductCode],
    [ProductName],
    [Description],
    [Brand],
    [Model],
    [CategoryId],
    [Category],
    [SubCategory],
    [Tags],
    [ProductType],
    [Status],
    [Weight],
    [Volume],
    [Dimensions],
    [UnitOfMeasure],
    [Color],
    [Material],
    [Size],
    [CostPrice],
    [SellingPrice],
    [WholesalePrice],
    [RetailPrice],
    [Currency],
    [TaxRate],
    [DiscountPercentage],
    [CurrentStock],
    [MinimumStock],
    [MaximumStock],
    [ReorderLevel],
    [ReorderQuantity],
    [StockLocation],
    [Barcode],
    [QRCode],
    [SKU],
    [PrimarySupplierId],
    [PrimarySupplierName],
    [SupplierPrice],
    [LeadTimeDays],
    [IsTaxable],
    [IsDiscountable],
    [IsReturnable],
    [ReturnPeriodDays],
    [MinimumOrderQuantity],
    [MaximumOrderQuantity],
    [ImageUrls],
    [DocumentUrls],
    [VideoUrl],
    [Notes],
    [MetaTitle],
    [MetaDescription],
    [MetaKeywords],
    [LastSoldDate],
    CAST(NULL AS NVARCHAR(20)) as [LastPurchaseDate],
    [TotalSold],
    [TotalPurchased],
    [TimesSold],
    [TimesPurchased],
    [AverageRating],
    [ReviewCount],
    CAST(PO.CreationTime AS NVARCHAR(20)) as [CreationTime],
    NULL as [CreatorId],
    CAST(PO.LastModificationTime AS NVARCHAR(20)) as [LastModificationTime],
    NULL as [LastModifierId],
    0 as [IsDeleted],
    NULL as [DeleterId],
    CAST(NULL AS NVARCHAR(20)) as [DeletionTime],
    NULL as [PrimarySupplierSKU],
    NULL as [SupplierSKU],
    NULL as [TotalSold],
    NULL as [TotalPurchased],
    0 as [TimesSold],
    0 as [TimesPurchased]
)
SELECT 
    NEWID() as [Id],
    'LG-' + REPLACE(PO.OrderNumber, 'PO-', '') as [ProductCode],
    'LG ' + PO.ProductName as [ProductName],
    'LG ' + PO.ProductName + ' - Premium Quality' as [Description],
    'LG' as [Brand],
    REPLACE(PO.ProductName, 'CNC Lathe Machine - ', '') as [Model],
    NULL as [CategoryId],
    'Manufacturing Equipment' as [Category],
    'Equipment' as [SubCategory],
    'LG,manufacturing,equipment,industrial' as [Tags],
    1 as [ProductType],
    1 as [Status],
    2500.0 as [Weight],
    2.5 as [Volume],
    '120" x 80" x 96"' as [Dimensions],
    'Units' as [UnitOfMeasure],
    'Silver/Gray' as [Color],
    'Steel/Aluminum' as [Material],
    'Large' as [Size],
    PO.Quantity * 5000.0 as [CostPrice],
    PO.Quantity * 7500.0 as [SellingPrice],
    PO.Quantity * 6000.0 as [WholesalePrice],
    PO.Quantity * 7500.0 as [RetailPrice],
    'USD' as [Currency],
    8.25 as [TaxRate],
    10.0 as [DiscountPercentage],
    CASE 
        WHEN PO.Status = 'Completed' THEN 50
        WHEN PO.Status IS NULL THEN 25
        ELSE 10
    END as [CurrentStock],
    5 as [MinimumStock],
    100 as [MaximumStock],
    15 as [ReorderLevel],
    25 as [ReorderQuantity],
    'Warehouse A - Manufacturing' as [StockLocation],
    'LG-' + REPLACE(PO.OrderNumber, 'PO-', '') as [Barcode],
    NULL as [QRCode],
    'LG-' + REPLACE(PO.OrderNumber, 'PO-', '') as [SKU],
    NULL as [PrimarySupplierId],
    'LG Manufacturing Division' as [PrimarySupplierName],
    PO.Quantity * 4500.0 as [SupplierPrice],
    30 as [LeadTimeDays],
    1 as [IsTaxable],
    1 as [IsDiscountable],
    1 as [IsReturnable],
    30 as [ReturnPeriodDays],
    1.0 as [MinimumOrderQuantity],
    10.0 as [MaximumOrderQuantity],
    '["https://example.com/lg-product.jpg"]' as [ImageUrls],
    '[]' as [DocumentUrls],
    NULL as [VideoUrl],
    PO.Notes as [Notes],
    'LG ' + REPLACE(PO.ProductName, 'CNC Lathe Machine - ', '') + ' - Premium Quality' as [MetaTitle],
    'High-quality LG manufacturing equipment for industrial applications' as [MetaDescription],
    'LG,manufacturing,equipment,industrial' as [MetaKeywords],
    4.5 as [AverageRating],
    CASE 
        WHEN PO.Status = 'Completed' THEN 25
        WHEN PO.Status IS NULL THEN 15
        ELSE 5
    END) as [ReviewCount],
    PO.CreationTime as [CreationTime],
    NULL as [CreatorId],
    CAST(PO.LastModificationTime AS NVARCHAR(20)) as [LastModificationTime],
    NULL as [LastModifierId],
    0 as [IsDeleted],
    NULL as [DeleterId],
    NULL as [DeletionTime],
    NULL as [PrimarySupplierSKU],
    NULL as [SupplierSKU],
    NULL as [TotalSold],
    NULL as [TotalPurchased],
    0 as [TimesSold],
    0 as [TimesPurchased]
FROM [dbo].[AppProductionOrders] PO
WHERE PO.ProductName LIKE '%CNC Lathe%' 
   OR PO.ProductName LIKE '%Assembly Line%' 
   OR PO.ProductName LIKE '%Industrial Steel%';

PRINT 'Successfully converted Production Orders to LG Products';

-- Declare a variable to hold the count
DECLARE @ProductCount INT;
SELECT @ProductCount = COUNT(*) FROM [dbo].[AppProducts] WHERE Brand = 'LG';
PRINT 'Total LG Products created: ' + CAST(@ProductCount AS NVARCHAR(10));
