import { RoutesService, eLayoutType } from '@abp/ng.core';
import { APP_INITIALIZER } from '@angular/core';

export const APP_ROUTE_PROVIDER = [
  { provide: APP_INITIALIZER, useFactory: configureRoutes, deps: [RoutesService], multi: true },
];

function configureRoutes(routesService: RoutesService) {
  return () => {
    routesService.add([
      {
        path: '/',
        name: '::Menu:Home',
        iconClass: 'fas fa-home',
        order: 1,
        layout: eLayoutType.application,
      },
      {
        path: '/manufacturing',
        name: 'Manufacturing',
        iconClass: 'fas fa-industry',
        order: 2,
        layout: eLayoutType.application,
      },
      {
        path: '/manufacturing/production-orders',
        name: 'Production Orders',
        iconClass: 'fas fa-tasks',
        order: 3,
        layout: eLayoutType.application,
        parentName: 'Manufacturing',
      },
      {
        path: '/manufacturing/work-orders',
        name: 'Work Orders',
        iconClass: 'fas fa-tools',
        order: 4,
        layout: eLayoutType.application,
        parentName: 'Manufacturing',
      },
      {
        path: '/manufacturing/maintenance',
        name: 'Maintenance',
        iconClass: 'fas fa-wrench',
        order: 5,
        layout: eLayoutType.application,
        parentName: 'Manufacturing',
      },
      {
        path: '/manufacturing/quality-control',
        name: 'Quality Control',
        iconClass: 'fas fa-check-circle',
        order: 6,
        layout: eLayoutType.application,
        parentName: 'Manufacturing',
      },
      {
        path: '/products',
        name: 'Products',
        iconClass: 'fas fa-box',
        order: 4,
        layout: eLayoutType.application,
      },
      {
        path: '/products/categories',
        name: 'Categories',
        iconClass: 'fas fa-tags',
        order: 6,
        layout: eLayoutType.application,
        parentName: 'Products',
      },
      {
        path: '/barcode',
        name: 'Barcode',
        iconClass: 'fas fa-barcode',
        order: 5,
        layout: eLayoutType.application,
      },
      {
        path: '/barcode/scanner',
        name: 'Scanner',
        iconClass: 'fas fa-qrcode',
        order: 6,
        layout: eLayoutType.application,
        parentName: 'Barcode',
      },
      {
        path: '/barcode/generator',
        name: 'Generator',
        iconClass: 'fas fa-plus',
        order: 7,
        layout: eLayoutType.application,
        parentName: 'Barcode',
      },
      {
        path: '/crm',
        name: 'Order Agency & Order Management',
        iconClass: 'fas fa-handshake',
        order: 6,
        layout: eLayoutType.application,
      },
      {
        path: '/crm/customers',
        name: 'Customers',
        iconClass: 'fas fa-users',
        order: 7,
        layout: eLayoutType.application,
        parentName: 'Order Agency & Order Management',
      },
      {
        path: '/crm/leads',
        name: 'Leads',
        iconClass: 'fas fa-lightbulb',
        order: 8,
        layout: eLayoutType.application,
        parentName: 'Order Agency & Order Management',
      },
      {
        path: '/crm/opportunities',
        name: 'Opportunities',
        iconClass: 'fas fa-chart-line',
        order: 9,
        layout: eLayoutType.application,
        parentName: 'Order Agency & Order Management',
      },
      {
        path: '/purchase',
        name: 'Purchase',
        iconClass: 'fas fa-shopping-cart',
        order: 7,
        layout: eLayoutType.application,
      },
      {
        path: '/purchase/orders',
        name: 'Purchase Orders',
        iconClass: 'fas fa-file-invoice',
        order: 8,
        layout: eLayoutType.application,
        parentName: 'Purchase',
      },
      {
        path: '/purchase/vendors',
        name: 'Vendors',
        iconClass: 'fas fa-truck',
        order: 9,
        layout: eLayoutType.application,
        parentName: 'Purchase',
      },
      {
        path: '/purchase/quotations',
        name: 'Quotations',
        iconClass: 'fas fa-file-alt',
        order: 10,
        layout: eLayoutType.application,
        parentName: 'Purchase',
      },
      {
        path: '/logistics',
        name: 'Delivery & Logistics Tracking',
        iconClass: 'fas fa-shipping-fast',
        order: 8,
        layout: eLayoutType.application,
      },
      {
        path: '/hrms',
        name: 'Personnel Affairs & HR Functions',
        iconClass: 'fas fa-users',
        order: 8,
        layout: eLayoutType.application,
      },
      {
        path: '/hrms/employees',
        name: 'Employees',
        iconClass: 'fas fa-user-tie',
        order: 9,
        layout: eLayoutType.application,
        parentName: 'Personnel Affairs & HR Functions',
      },
      {
        path: '/hrms/attendance',
        name: 'Attendance',
        iconClass: 'fas fa-clock',
        order: 10,
        layout: eLayoutType.application,
        parentName: 'Personnel Affairs & HR Functions',
      },
      {
        path: '/hrms/leave',
        name: 'Leave Management',
        iconClass: 'fas fa-calendar-alt',
        order: 11,
        layout: eLayoutType.application,
        parentName: 'Personnel Affairs & HR Functions',
      },
      {
        path: '/accounting',
        name: 'Settlement & Accounting Integration',
        iconClass: 'fas fa-calculator',
        order: 9,
        layout: eLayoutType.application,
      },
      {
        path: '/accounting/invoices',
        name: 'Invoices',
        iconClass: 'fas fa-file-invoice',
        order: 10,
        layout: eLayoutType.application,
        parentName: 'Settlement & Accounting Integration',
      },
      {
        path: '/accounting/payments',
        name: 'Payments',
        iconClass: 'fas fa-credit-card',
        order: 11,
        layout: eLayoutType.application,
        parentName: 'Settlement & Accounting Integration',
      },
      {
        path: '/accounting/expenses',
        name: 'Expenses',
        iconClass: 'fas fa-receipt',
        order: 12,
        layout: eLayoutType.application,
        parentName: 'Settlement & Accounting Integration',
      },
      {
        path: '/accounting/reports',
        name: 'Financial Reports',
        iconClass: 'fas fa-chart-pie',
        order: 13,
        layout: eLayoutType.application,
        parentName: 'Settlement & Accounting Integration',
      },
      {
        path: '/administration',
        name: 'Administration',
        iconClass: 'fas fa-cogs',
        order: 10,
        layout: eLayoutType.application,
      },
      {
        path: '/identity',
        name: 'Identity Management',
        iconClass: 'fas fa-users-cog',
        order: 11,
        layout: eLayoutType.application,
        parentName: 'Administration',
      },
      {
        path: '/tenant-management',
        name: 'Tenant Management',
        iconClass: 'fas fa-building',
        order: 12,
        layout: eLayoutType.application,
        parentName: 'Administration',
      },
      {
        path: '/setting-management',
        name: 'Settings',
        iconClass: 'fas fa-cog',
        order: 13,
        layout: eLayoutType.application,
        parentName: 'Administration',
      },
      {
        path: '/account',
        name: 'Account',
        iconClass: 'fas fa-user',
        order: 14,
        layout: eLayoutType.application,
        parentName: 'Administration',
      },
      ]);
  };
}
